### ISSUE TITLE
DGC2 MIV_ESS Bootstrap design issue

### ISSUE THREAD

**Issue by seb-slowik** [MiV-soft-RISCV-cores-on-Microchip-FPGAs/Future-Avalanche-Board#20]
There is an issue with the bootstrap design in the `Future-Avalanche-Board` repository. Specifically, the MIV_ESS Design Guide Configuration design - DGC2 I2C-Boot - has a problem where the MIV_RV32's RESETN signal is improperly connected to the main central reset network instead of the MIV_ESS's reset controller signal (CPU_RESETN). This is causing problems with the soft-processor core, preventing it from resetting after boot copy from external memory (I2C) has completed. Additionally, the DGC2 design has an output GPIO interrupt (GPIO_INT) signal on the MIV_ESS component floating

The affected configurations are:
- DGC2 (MIV_ESS Design Guide Configuration 2 featuring I2C-Boot)

Resolution:
* Bootstrap sequence is incomplete, unless MIV_ESS can reset MIV_RV32. It is necessary to connect the `RESETN` signal from MIV_RV32 to the `CPU_RESETN` signal on MIV_ESS.
* As the `GPIO_INT[3:0]` port on MIV_ESS is unused, it needs to be marked-off as unused.
* The top-level signal `GPIO_IN[1:0]`, which is currently unconstrained to any fabric pin and causing a warning, needs to be removed and tied low on the MIV_ESS component in the design, as intended.

**Comment by CLappin** [comment]
Fixes applied to the main branch.
